"""
Itinerary Builder

Assembles the final ItineraryResponse from pipeline outputs and
optional LLM-generated text.  No planning logic lives here.

LLM content (overview, narratives, poi_reasons) is passed in as
pre-computed values so this module stays a pure assembly step.
"""

import logging
from collections import Counter
from datetime import datetime, timezone

from app.schemas.common import POICategory
from app.schemas.itinerary import DayPlan, DailyWeather, ItineraryResponse
from app.schemas.persona import TravelerPersona
from app.schemas.poi import ScheduledPOI
from app.schemas.trip_request import TripRequest

logger = logging.getLogger(__name__)

_CATEGORY_THEMES: dict[POICategory, str] = {
    POICategory.history_culture: "History & Culture",
    POICategory.nature_scenery:  "Nature & Scenery",
    POICategory.food_dining:     "Food & Dining",
    POICategory.shopping:        "Shopping",
    POICategory.art_museum:      "Art & Museums",
    POICategory.entertainment:   "Entertainment",
    POICategory.local_life:      "Local Life",
}


class ItineraryBuilder:
    """Assembles a complete ItineraryResponse from pipeline outputs."""

    def build(
        self,
        request_id: str,
        request: TripRequest,
        persona: TravelerPersona,
        days_scheduled: list[list[ScheduledPOI]],
        weather_list: list[DailyWeather] | None = None,
        # ── LLM-generated content (all optional) ─────────────────────────────
        overview: str = "",
        day_narratives: list[str] | None = None,
        poi_reasons: dict[str, str] | None = None,
    ) -> ItineraryResponse:
        """
        Parameters
        ----------
        request_id      : UUID string generated by TripPlanner.
        request         : Original trip request.
        persona         : Built persona used for planning.
        days_scheduled  : list[list[ScheduledPOI]] — one inner list per day.
        weather_list    : Optional per-day weather forecasts.
        overview        : LLM-generated trip introduction (empty if mock/not available).
        day_narratives  : LLM-generated narrative per day (index-aligned with days_scheduled).
        poi_reasons     : Mapping of poi.id → one-sentence recommendation reason.
        """
        total_cost = sum(
            sp.poi.avg_cost_cny
            for day_pois in days_scheduled
            for sp in day_pois
        )

        day_plans: list[DayPlan] = []
        planning_notes: list[str] = []

        for i, day_pois in enumerate(days_scheduled):
            day_number = i + 1
            weather = (
                weather_list[i]
                if weather_list and i < len(weather_list)
                else None
            )
            theme = _day_theme(day_pois)
            narrative = (
                day_narratives[i]
                if day_narratives and i < len(day_narratives)
                else ""
            )

            # Apply recommendation reasons to ScheduledPOI objects.
            if poi_reasons:
                for sp in day_pois:
                    reason = poi_reasons.get(sp.poi.id, "")
                    if reason:
                        sp.recommendation_reason = reason

            if not day_pois:
                planning_notes.append(
                    f"Day {day_number}: no POIs available after allocation "
                    "(pool may be exhausted)."
                )

            day_plans.append(
                DayPlan(
                    day_number=day_number,
                    date_label=f"Day {day_number}",
                    theme=theme,
                    pois=day_pois,
                    weather=weather,
                    narrative=narrative,
                    tips=[],
                )
            )

        logger.info(
            "ItineraryBuilder: assembled %d-day itinerary for '%s' (¥%.0f)",
            len(day_plans),
            request.destination,
            total_cost,
        )

        return ItineraryResponse(
            request_id=request_id,
            destination=request.destination,
            duration_days=request.duration_days,
            overview=overview,
            persona_summary=persona.persona_summary,
            days=day_plans,
            total_estimated_cost_cny=round(total_cost, 2),
            generated_at=datetime.now(timezone.utc),
            planning_notes=planning_notes,
        )


def _day_theme(day_pois: list[ScheduledPOI]) -> str:
    """
    Return a human-readable theme label for a day.

    When a clear secondary category is present (runner-up count ≥ half of
    dominant), a blended label is returned (e.g. "Food & Dining · Local Life")
    so multi-interest days are accurately reflected in the UI and LLM prompts.
    """
    if not day_pois:
        return "Free Day"
    counter = Counter(sp.poi.category for sp in day_pois)
    top = counter.most_common(2)
    dominant: POICategory = top[0][0]
    dominant_label = _CATEGORY_THEMES.get(dominant, "Mixed")

    if len(top) == 2:
        runner_up_count = top[1][1]
        dominant_count  = top[0][1]
        # Blend when runner-up is significant (≥ half of dominant count).
        if runner_up_count >= max(1, dominant_count // 2):
            runner_up_label = _CATEGORY_THEMES.get(top[1][0], "Mixed")
            return f"{dominant_label} · {runner_up_label}"

    return dominant_label
