"""
Itinerary Builder

Assembles the final ItineraryResponse from the outputs of all four pipeline
stages.  No planning logic lives here — this module is pure data assembly.

LLM-generated fields (overview, narrative, tips, recommendation_reason) are
left as empty strings in Sprint 2.  Sprint 4 will fill them in.
"""

import logging
from collections import Counter
from datetime import datetime, timezone

from app.schemas.common import POICategory
from app.schemas.itinerary import DayPlan, DailyWeather, ItineraryResponse
from app.schemas.persona import TravelerPersona
from app.schemas.poi import ScheduledPOI
from app.schemas.trip_request import TripRequest

logger = logging.getLogger(__name__)

# Human-readable day themes derived from the dominant POI category.
_CATEGORY_THEMES: dict[POICategory, str] = {
    POICategory.history_culture: "History & Culture",
    POICategory.nature_scenery:  "Nature & Scenery",
    POICategory.food_dining:     "Food & Dining",
    POICategory.shopping:        "Shopping",
    POICategory.art_museum:      "Art & Museums",
    POICategory.entertainment:   "Entertainment",
    POICategory.local_life:      "Local Life",
}


class ItineraryBuilder:
    """Assembles a complete ItineraryResponse from pipeline outputs."""

    def build(
        self,
        request_id: str,
        request: TripRequest,
        persona: TravelerPersona,
        days_scheduled: list[list[ScheduledPOI]],
        weather_list: list[DailyWeather] | None = None,
    ) -> ItineraryResponse:
        """
        Parameters
        ----------
        request_id      : UUID string generated by TripPlanner.
        request         : Original trip request.
        persona         : Built persona used for planning.
        days_scheduled  : List of ScheduledPOI lists, one per day
                          (produced by RouteOptimizer).
        weather_list    : Optional per-day weather forecasts.

        Returns
        -------
        ItineraryResponse ready to be serialised and returned via the API.
        """
        total_cost = sum(
            sp.poi.avg_cost_cny
            for day_pois in days_scheduled
            for sp in day_pois
        )

        day_plans: list[DayPlan] = []
        planning_notes: list[str] = []

        for i, day_pois in enumerate(days_scheduled):
            day_number = i + 1
            weather = (
                weather_list[i]
                if weather_list and i < len(weather_list)
                else None
            )
            theme = _day_theme(day_pois)

            if not day_pois:
                planning_notes.append(
                    f"Day {day_number}: no POIs available after allocation "
                    "(pool may be exhausted)."
                )

            day_plans.append(
                DayPlan(
                    day_number=day_number,
                    date_label=f"Day {day_number}",
                    theme=theme,
                    pois=day_pois,
                    weather=weather,
                    narrative="",          # filled by LLM in Sprint 4
                    tips=[],               # filled by LLM in Sprint 4
                )
            )

        logger.info(
            "ItineraryBuilder: assembled %d-day itinerary for '%s' "
            "(total cost ≈ ¥%.0f)",
            len(day_plans),
            request.destination,
            total_cost,
        )

        return ItineraryResponse(
            request_id=request_id,
            destination=request.destination,
            duration_days=request.duration_days,
            overview="",                   # filled by LLM in Sprint 4
            persona_summary=persona.persona_summary,
            days=day_plans,
            total_estimated_cost_cny=round(total_cost, 2),
            generated_at=datetime.now(timezone.utc),
            planning_notes=planning_notes,
        )


# ── Module-level helpers ───────────────────────────────────────────────────────

def _day_theme(day_pois: list[ScheduledPOI]) -> str:
    """Derive a human-readable theme from the most common POI category."""
    if not day_pois:
        return "Free Day"
    counter = Counter(sp.poi.category for sp in day_pois)
    dominant_category: POICategory = counter.most_common(1)[0][0]
    return _CATEGORY_THEMES.get(dominant_category, "Mixed")
